[package]
name = "hexga_asset"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
readme = "README.md"

description = "A crossplatform way to load file, and factorize them into asset, and hot reload them."
categories = ["filesystem", "encoding", "data-structures"]

[features]
default = ["serde", "serde_rc", "hexga_encoding_derive"]

serde = ["dep:serde", "hexga_io/serde", "hexga_encoding/serde", "hexga_core/serde", "hexga_utils/serde"]
serde_rc = ["serde/rc",  "hexga_io/serde_rc", "hexga_encoding/serde_rc", "hexga_core/serde_rc", "hexga_utils/serde_rc"]

hexga_encoding_derive = ["hexga_encoding/derive"]
print_io = ["hexga_io/print_io"]

[dependencies]
serde = { version = "1.0.0", optional = true }
hexga_io.workspace = true
hexga_encoding.workspace = true
#hexga_save.workspace = true
hexga_utils.workspace = true
hexga_core.workspace = true
