[package]
name = "hexga_engine"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

keywords = []
description = "Hexga Game Engine"
categories = ["game-development", "rendering", "multimedia", "graphics"]

[features]
default = ["serde", "int_are_32_bits", "float_are_32_bits"]

int_are_8_bits    = ["hexga_engine_core/int_are_8_bits"]
int_are_16_bits   = ["hexga_engine_core/int_are_16_bits"]
int_are_32_bits   = ["hexga_engine_core/int_are_32_bits"]
int_are_64_bits   = ["hexga_engine_core/int_are_64_bits"]
int_are_size_bits = ["hexga_engine_core/int_are_size_bits"]

float_are_32_bits   = ["hexga_engine_core/float_are_32_bits"]
float_are_64_bits   = ["hexga_engine_core/float_are_64_bits"]
float_are_size_bits = ["hexga_engine_core/float_are_size_bits"]

serde = ["dep:serde", "hexga_engine_core/serde"]

[dependencies]
hexga_engine_core.workspace = true

serde = { version = "1.0.0", features = ["derive"], optional = true }

