[package]
name = "hexga_engine_events"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

keywords = []
description = "Events interface for the Hexga Engine"
categories = []

[features]
default = ["serde"]

serde = ["dep:serde"]

[dependencies]
hexga_core.workspace = true

serde = { version = "1.0.0", features = ["derive"], optional = true }

