[package]
name = "io_test"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true


[features]
default = ["serde", "hexga_io", "hexga_io_rc"]

serde = ["dep:serde",
    "hexga/serde"
]
hexga_io = ["dep:hexga_io", "hexga_io/derive", "serde",
    "hexga/hexga_io"
]
hexga_io_rc = ["hexga_io", "hexga_io/rc", "serde", "serde/rc",
    "hexga/hexga_io_rc"
]

[dependencies]
hexga.workspace = true

serde = { version = "1.0.0", features = ["derive"], optional = true }
hexga_io = { workspace = true, optional = true }
