[package]
name = "hexga_typedef"
version = "0.0.1"
edition = "2024"
authors = ["Mewily <thomas.mewily@gmail.com>"]
keywords = ["math", "number"]
description = "Provide a common typedef for `float`, `int` and `uint`. The precision can be changed with feature flags and can be easily shared across multiple crates."
license = "MIT OR Apache-2.0"
categories = ["mathematics", "rust-patterns"]
repository = "https://github.com/Thomas-Mewily/hexga_typedef"

[features]
default = ["int_are_32_bits", "float_are_32_bits"]

int_are_8_bits    = []
int_are_16_bits   = []
int_are_32_bits   = []
int_are_64_bits   = []
int_are_size_bits = []

float_are_32_bits   = []
float_are_64_bits   = []
float_are_size_bits = []

[dependencies]
