[package]
name = "hexga_slot"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"

keywords = []
description = ""
categories = ["rust-patterns", "data-structures"]

[dependencies]
hexga_core.workspace = true