[package]
name = "test2"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[features]
default = [
            "int_are_32_bits", "float_are_32_bits",
            "serde", "hexga_io",
            "serde_json", "serde_ron", "serde_xml", "serde_quick_bin"
          ]

int_are_8_bits    = ["hexga/int_are_8_bits"]
int_are_16_bits   = ["hexga/int_are_16_bits"]
int_are_32_bits   = ["hexga/int_are_32_bits"]
int_are_64_bits   = ["hexga/int_are_64_bits"]
int_are_size_bits = ["hexga/int_are_size_bits"]

float_are_32_bits   = ["hexga/float_are_32_bits"]
float_are_64_bits   = ["hexga/float_are_64_bits"]
float_are_size_bits = ["hexga/float_are_size_bits"]

serde           = ["hexga/serde"]
hexga_io        = ["hexga/hexga_io", "serde"]

serde_json      = ["hexga/serde_json"]
serde_ron       = ["hexga/serde_ron"]
serde_xml       = ["hexga/serde_xml"]
serde_quick_bin = ["hexga/serde_quick_bin"]

[dependencies]
hexga.workspace = true
hexga_map_on.workspace = true
hexga_graphics.workspace = true
#hexga_graphics.workspace = true
hexga_generational.workspace = true
hexga_engine.workspace = true