[package]
name = "hexga_io"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
readme = "README.md"

keywords = []
description = "io abstraction"
categories = ["filesystem"]

[features]
default = ["serde_json", "serde_ron", "serde_xml", "serde_quick_bin",
    "rc"
]

rc  = ["serde/rc"]

serde_ron   = ["dep:ron"]
serde_json  = ["dep:serde_json"]
serde_xml   = ["dep:quick-xml"]
serde_quick_bin  = ["dep:bincode"]

[dependencies]
serde = { version = "1.0.0", features = ["derive"] }
hexga_core.workspace = true

# markup language :
ron = { version = "0.10.1", optional = true }
serde_json = { version = "1.0.133", optional = true }
quick-xml = { version = "0.37.1", features = ["serialize"], optional = true }
bincode = { version = "1.3.3", optional = true }
