[package]
name = "hexga_engine_render"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

keywords = []
description = "Rendering interface for the Hexga Engine"
categories = []

[features]
default = [
    "serde", "hexga_io",
    "int_are_32_bits", "float_are_32_bits"
]

int_are_8_bits    = ["hexga_math/int_are_8_bits", "hexga_graphics/int_are_8_bits"]
int_are_16_bits   = ["hexga_math/int_are_16_bits", "hexga_graphics/int_are_16_bits"]
int_are_32_bits   = ["hexga_math/int_are_32_bits", "hexga_graphics/int_are_32_bits"]
int_are_64_bits   = ["hexga_math/int_are_64_bits", "hexga_graphics/int_are_64_bits"]
int_are_size_bits = ["hexga_math/int_are_size_bits", "hexga_graphics/int_are_size_bits"]

float_are_32_bits   = ["hexga_math/float_are_32_bits", "hexga_graphics/float_are_32_bits"]
float_are_64_bits   = ["hexga_math/float_are_64_bits", "hexga_graphics/float_are_64_bits"]
float_are_size_bits = ["hexga_math/float_are_size_bits", "hexga_graphics/float_are_size_bits"]

hexga_io = ["dep:hexga_io", "serde", "hexga_math/hexga_io", "hexga_graphics/hexga_io"]
serde = ["dep:serde", "hexga_math/serde", "hexga_graphics/serde"]

[dependencies]
hexga_math.workspace = true
hexga_graphics.workspace = true
hexga_io = { workspace = true, optional = true }

serde = { version = "1.0.0", features = ["derive"], optional = true }
