[package]
name = "hexga_test"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[features]
default = [
            "int_are_32_bits", "float_are_32_bits",
            "serde", 
            #"serde_json", "serde_ron", "serde_xml", "serde_quick_bin"
          ]

int_are_8_bits    = ["quad_hexga_engine/int_are_8_bits"]
int_are_16_bits   = ["quad_hexga_engine/int_are_16_bits"]
int_are_32_bits   = ["quad_hexga_engine/int_are_32_bits"]
int_are_64_bits   = ["quad_hexga_engine/int_are_64_bits"]
int_are_size_bits = ["quad_hexga_engine/int_are_size_bits"]

float_are_32_bits   = ["quad_hexga_engine/float_are_32_bits"]
float_are_64_bits   = ["quad_hexga_engine/float_are_64_bits"]
float_are_size_bits = ["quad_hexga_engine/float_are_size_bits"]

serde           = ["quad_hexga_engine/serde"]

# serde_json      = ["hexga/serde_json"]
# serde_ron       = ["hexga/serde_ron"]
# serde_xml       = ["hexga/serde_xml"]
# serde_quick_bin = ["hexga/serde_quick_bin"]

[dependencies]
#hexga.workspace = true
#hexga_graphics.workspace = true
#hexga_generational.workspace = true
quad_hexga_engine.workspace = true
#criterion = "0.5.1"
#hexga_generational = "0.0.5"