[package]
name = "hexga_engine_window"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

keywords = []
description = "Window interface for the Hexga Engine"
categories = []

[features]
default = [
    "serde", "hexga_io",
    "int_are_32_bits", "float_are_32_bits"
]

int_are_8_bits    = ["hexga_math/int_are_8_bits", "hexga_engine_events/int_are_8_bits", "hexga_graphics/int_are_8_bits"]
int_are_16_bits   = ["hexga_math/int_are_16_bits", "hexga_engine_events/int_are_16_bits", "hexga_graphics/int_are_16_bits"]
int_are_32_bits   = ["hexga_math/int_are_32_bits", "hexga_engine_events/int_are_32_bits", "hexga_graphics/int_are_32_bits"]
int_are_64_bits   = ["hexga_math/int_are_64_bits", "hexga_engine_events/int_are_64_bits", "hexga_graphics/int_are_64_bits"]
int_are_size_bits = ["hexga_math/int_are_size_bits", "hexga_engine_events/int_are_size_bits", "hexga_graphics/int_are_size_bits"]

float_are_32_bits   = ["hexga_math/float_are_32_bits", "hexga_engine_events/float_are_32_bits", "hexga_graphics/float_are_32_bits"]
float_are_64_bits   = ["hexga_math/float_are_64_bits", "hexga_engine_events/float_are_64_bits", "hexga_graphics/float_are_64_bits"]
float_are_size_bits = ["hexga_math/float_are_size_bits", "hexga_engine_events/float_are_size_bits", "hexga_graphics/float_are_size_bits"]

serde = ["dep:serde", "hexga_math/serde", "hexga_engine_events/serde", "hexga_graphics/serde", "hexga_generational/serde", "hexga_bitflags/serde"]
hexga_io = ["dep:hexga_io", "dep:hexga_io_derive", "serde", "hexga_math/hexga_io", "hexga_engine_events/hexga_io", "hexga_graphics/hexga_io", "hexga_generational/hexga_io", "hexga_bitflags/hexga_io"]

[dependencies]
hexga_core.workspace = true
hexga_math.workspace = true
hexga_graphics.workspace = true
hexga_engine_events.workspace = true
hexga_generational.workspace = true
hexga_bitflags.workspace = true

hexga_io = { workspace = true, optional = true }
hexga_io_derive = { workspace = true, optional = true }

serde = { version = "1.0.0", features = ["derive"], optional = true }
winit = "0.30.11"
copypasta = "0.10.2"