[package]
name = "hexga_engine_backend_quad"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

keywords = []
description = "An implementation of the Hexga Engine Core using MiniQuad"
categories = []

[features]
default = [
    "serde", "hexga_io",
    "int_are_32_bits", "float_are_32_bits"
]

int_are_8_bits    = ["hexga_engine_core/int_are_8_bits"]
int_are_16_bits   = ["hexga_engine_core/int_are_16_bits"]
int_are_32_bits   = ["hexga_engine_core/int_are_32_bits"]
int_are_64_bits   = ["hexga_engine_core/int_are_64_bits"]
int_are_size_bits = ["hexga_engine_core/int_are_size_bits"]

float_are_32_bits   = ["hexga_engine_core/float_are_32_bits"]
float_are_64_bits   = ["hexga_engine_core/float_are_64_bits"]
float_are_size_bits = ["hexga_engine_core/float_are_size_bits"]

serde = ["dep:serde", "hexga_engine_core/serde"]
hexga_io = ["dep:hexga_io", "hexga_io/derive", "serde", "hexga_engine_core/hexga_io"]

[dependencies]
hexga_engine_core.workspace = true
hexga_io = { workspace = true, optional = true }
hexga_io_derive = { workspace = true, optional = true }

miniquad = "0.4.8"
serde = { version = "1.0.0", features = ["derive"], optional = true }