[package]
name = "hexga_bitflags"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
readme = "README.md"

keywords = ["bitflags"]
description = "Bitflags utilities"
categories = ["rust-patterns"]

[features]
default = ["serde", "hexga_io"]

serde = ["dep:serde"]
hexga_io = ["dep:hexga_io", "hexga_io/derive", "serde"]

[dependencies]
hexga_number.workspace = true
hexga_io = { workspace = true, optional = true }

serde = { version = "1.0.0", features = ["derive"], optional = true }
